language: ruby

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t roblobob/dopamine-dev .
  - docker run -t roblobob/dopamine-dev /bin/sh -c "cd /app; yarn build;"
  - docker ps -a
  - docker run -t roblobob/dopamine-dev /bin/sh -c "cd /app; yarn test;"

script:
  - docker build -t roblobob/dopamine-mvp .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
